add an email of phone transformer
Multiverse-io/anonymiser pull request #126
Opened 2024-02-09 20:02 UTC by danturn

Heya y'all!

hope you're well, 

i had the need to be able to anonymise a field that was either a phone number OR an email (depending on a `type` variable in another column... i don't think we can couple one column to another so thought this was a better approach... 

wdyt? its pretty simple?

i also added all non General data types to the csv output as i think it makes more sense? you can always filter out the ones you dont need in the csv right?

lmk if this seems sensible!

Dan

2024-04-22 09:12 UTC, danturn commented
@hoyon do you reckon y'all might look at this? if its not something you want  and dont want to merge it that is also fine!

2024-04-26 16:08 UTC, hoyon commented on README.md
> +- Random email address from [faker](https://github.com/cksac/fake-rs)
```suggestion
- FakeEmailOrPhone * - Either a random phone number OR a random email depending on whether the existing data starts with a `+` and doesn't contain an `@` symbol or not!
```

2024-04-26 16:09 UTC, hoyon approved these changes

2024-04-26 16:16 UTC, hoyon requested changes
@danturn there are clippy issues. Can you take a look at fixing them? Otherwise it looks good.

2024-04-29 08:48 UTC, danturn commented
> @danturn there are clippy issues. Can you take a look at fixing them? Otherwise it looks good.

@hoyon sorted, sorry thought i had done that already!

if you get a sec could you look at the gzip pr as well?

2024-04-29 08:56 UTC, danturn commented
> > @danturn there are clippy issues. Can you take a look at fixing them? Otherwise it looks good.
> 
> @hoyon sorted, sorry thought i had done that already!
> 
> if you get a sec could you look at the gzip pr as well?

also, sorry @hoyon i cant see why the build is failing now, 

`build_and_test` runs without error for me locally..

2024-04-29 08:58 UTC, hoyon commented
@danturn the build is failing due to a circleci permission issue. I'm not sure how to fix it. Let me merge another dependabot PR and then hit update branch and maybe it'll be happy with that.

2024-04-29 09:37 UTC, hoyon approved these changes

2024-04-29 09:37 UTC, merged